# Conclusion

In this project, we discover the correlation between latitude and year and between elevation and year of Australia popular research native plants in the last 50 years. The result we conclude is not quite significant since global warming is a much longer process. And because many other factors can impact plants living such as rainfall, illumination and human factors, the living area of plants is not stable and the minor change of temperature might have a little impact on it. But we still find something in this minor changes. In the result of correlation between latitude and year we can find that the number of negative correlation is much larger than the positive one, which means that plants which have correlation are more likely to live in higher latitude area with years pass. In the result of correlation between elevation and year we can find that the number of positive correlation is much larger than the negative one, which means that plants which have correlation are more likely to live in higher elevation area with years pass. These results imply that native plants in Australia have a tendency to live in higher latitude and elevation area, which further reveal global warming somehow. 